version: '3.8'

networks:
  web_net:
    external: true
    name: web_net

volumes:
  portainer_data:
    name: portainer_data

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: on-failure
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    networks:
      - web_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web_net"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`gui.docker.mecan.ir`)"
      - "traefik.http.routers.portainer.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`gui.docker.mecan.ir`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.tls.options=default"
      - "traefik.http.routers.portainer-secure.tls.certresolver=mycert"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"